import Image, { type ImageProps } from "next/image";
import blurMap from "@/lib/blur-map.json";

/**
 * SmartImage — next/image with automatic blur-up placeholders.
 *
 * The blur manifest (src/lib/blur-map.json, generated by
 * scripts/gen-blur-map.py) maps every /images/* asset to a 12px base64
 * JPEG. Colors paint instantly; the sharp image fades in over them —
 * no blank grey rectangles, no layout jank, Core-Web-Vitals-friendly.
 *
 * Falls back gracefully to no placeholder for unknown paths (e.g. new
 * images added without re-running the generator).
 */
type SmartImageProps = Omit<ImageProps, "placeholder" | "blurDataURL"> & {
  /** Force blur placeholder even for unlisted paths (uses neutral tint) */
  fallbackBlur?: boolean;
};

const NEUTRAL_BLUR =
  "data:image/jpeg;base64,/9j/4AAQSkZJRgABAQEASABIAAD/2wBDACgcHiMeGSgjISMtKxwI+7hZeOtYfL2GZS+YnxUkK5PSmSJKC+xsmIkOQdH5X/9k=";

export function SmartImage({
  src,
  fallbackBlur = true,
  ...props
}: SmartImageProps) {
  const key = typeof src === "string" ? src : "";
  const blurDataURL = (blurMap as Record<string, string>)[key];

  if (blurDataURL) {
    return <Image src={src} placeholder="blur" blurDataURL={blurDataURL} {...props} />;
  }
  if (fallbackBlur) {
    return <Image src={src} placeholder="blur" blurDataURL={NEUTRAL_BLUR} {...props} />;
  }
  return <Image src={src} {...props} />;
}
